CREATE TABLE STTM_STDGRCODH_MASTER (
Group_code varchar2(35),
Description varchar2(255),
Exposure_category varchar2(35),
Group_status varchar2(35),
Since Date,
Group_Type varchar2(35),
AUTH_STAT	CHAR (2) DEFAULT 'U',
CHECKER_DT_STAMP	DATE,
CHECKER_ID	VARCHAR2 (35),
MAKER_DT_STAMP	DATE ,
MAKER_ID	VARCHAR2 (12),
MOD_NO	NUMBER (4,0),
ONCE_AUTH	CHAR (1) DEFAULT 'N',
RECORD_STAT	CHAR (2) DEFAULT 'O',
CONSTRAINT PK_STTM_STDGRCODH_MASTER PRIMARY KEY (Group_code)
);
create OR REPLACE synonym STTMS_STDGRCODH_MASTER for STTM_STDGRCODH_MASTER;