DROP TABLE STTM_STDGRCODH_MASTER;
DROP TABLE STTM_STDGRCODH_DETAIL;

CREATE TABLE STTM_STDGRCODH_MASTER (
Group_code varchar2(35),
Description varchar2(255),
Exposure_category varchar2(35),
Group_status varchar2(35),
Since Date,
Group_Type varchar2(35),
AUTH_STAT	CHAR (2) DEFAULT 'U',
CHECKER_DT_STAMP	DATE,
CHECKER_ID	VARCHAR2 (35),
MAKER_DT_STAMP	DATE ,
MAKER_ID	VARCHAR2 (12),
MOD_NO	NUMBER (4,0),
ONCE_AUTH	CHAR (1) DEFAULT 'N',
RECORD_STAT	CHAR (2) DEFAULT 'O',
CONSTRAINT PK_STTM_STDGRCODH_MASTER PRIMARY KEY (Group_code)
);
create OR REPLACE synonym STTMS_STDGRCODH_MASTER for STTM_STDGRCODH_MASTER;



CREATE TABLE STTM_STDGRCODH_DETAIL (
Group_code varchar2(35),
Description varchar2(255),
Exposure_category varchar2(35),
Group_Status varchar2(35),
Since Date,
Group_Type varchar2(35),
CONSTRAINT PK_STTM_STDGRCODH_DETAIL PRIMARY KEY (Group_code)
);
create OR REPLACE synonym STTMS_STDGRCODH_DETAIL for STTM_STDGRCODH_DETAIL;

drop table LOVTABLE;
CREATE TABLE LOVTABLE
(
CATEGORY VARCHAR2(35)
);

INSERT INTO LOVTABLE VALUES ( 'First value');
INSERT INTO LOVTABLE VALUES ( 'Second value');
COMMIT;
SELECT CATEGORY FROM LOVTABLE;
DROP TABLE STTM_STDGRCODH_DETAIL;
DROP SYNONYM STTMS_STDGRCODH_DETAIL;
